identity_controllers:
    resource:
        path: ../src/Identity/Infrastructure/Http/Controller/
        namespace: App\Identity\Infrastructure\Http\Controller
    type: attribute

catalog_controllers:
    resource:
        path: ../src/Catalog/Infrastructure/Http/Controller/
        namespace: App\Catalog\Infrastructure\Http\Controller
    type: attribute

inventory_controllers:
    resource:
        path: ../src/Inventory/Infrastructure/Http/Controller/
        namespace: App\Inventory\Infrastructure\Http\Controller
    type: attribute

cart_controllers:
    resource:
        path: ../src/Cart/Infrastructure/Http/Controller/
        namespace: App\Cart\Infrastructure\Http\Controller
    type: attribute
