# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    App\Identity\Infrastructure\Http\Controller\:
        resource: '../src/Identity/Infrastructure/Http/Controller'
        tags: [ 'controller.service_arguments' ]
        public: true

    App\Identity\Application\Service\:
        resource: '../src/Identity/Application/Service/*Handler.php'
        tags: [ { name: tactician.handler, typehints: true } ]

    App\Identity\Domain\Model\UserRepository:
        alias: App\Identity\Infrastructure\Persistence\Doctrine\DoctrineUserRepository

    App\Catalog\Application\Service\:
        resource: '../src/Catalog/Application/Service/**/*Handler.php'
        tags: [ { name: tactician.handler, typehints: true } ]

    App\Catalog\Domain\Model\Category\CategoryRepository:
        alias: App\Catalog\Infrastructure\Persistence\Doctrine\Category\DoctrineCategoryRepository

    App\Catalog\Domain\Model\Product\ProductRepository:
        alias: App\Catalog\Infrastructure\Persistence\Doctrine\Product\DoctrineProductRepository

    App\Inventory\Domain\Model\StockItemRepository:
        alias: App\Inventory\Infrastructure\Persistence\Doctrine\DoctrineStockItemRepository

    App\Inventory\Application\Service\:
        resource: '../src/Inventory/Application/Service/*Handler.php'
        tags: [ { name: tactician.handler, typehints: true } ]


    App\Cart\Application\Service\:
        resource: '../src/Cart/Application/Service/**/*Handler.php'
        tags: [ { name: tactician.handler, typehints: true } ]

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
